#pragma once

#define APPLICATION_WIDTH 512
#define APPLICATION_HEIGHT 512
#define SCALE_FACTOR 5
#define TEXTURE_WIDTH (APPLICATION_WIDTH * SCALE_FACTOR)
#define TEXTURE_HEIGHT (APPLICATION_HEIGHT * SCALE_FACTOR)

void pause(void);

